name: farfromhome
description: version 1.0

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.0.3
  firebase_analytics: ^8.0.0
  firebase_auth: ^1.1.0
  google_sign_in: ^5.0.2
  cloud_firestore: ^1.0.5
  cached_network_image: ^3.0.0
  flutter_swiper_null_safety: ^1.0.2
  carousel_slider: ^3.0.0
  firebase_storage: ^8.0.3
  multi_image_picker: ^4.5.5
  flutter_custom_clippers: ^2.0.0
  font_awesome_flutter: ^9.0.0
  fluttertoast: ^8.0.4
  intl: ^0.17.0
  flutter_staggered_grid_view:
  connectivity:
  http:
  flutter_secure_storage:
  flutter_launcher_icons: ^0.9.0
  url_launcher: ^6.0.3
  razorpay_flutter: ^1.2.9
  flutter_statusbarcolor_ns: ^0.4.0
  flutter_range_slider_ns: ^0.0.1
  responsive_container_ns: ^0.0.1
  search_bar_ns: ^0.0.1

  pdf: ^3.2.0

  printing: ^5.1.0
  qr:

flutter_icons:
  ios: true
  android: true
  image_path: "assets/icons/logo_inverted.png"
  
dev_dependencies:

  flutter_test:
    sdk: flutter
    

dependency_overrides:
  platform: ^3.1.0
  
  

  # adaptive_icon_background: "assets/launcher/background.png"
  # adaptive_icon_foreground: "assets/launcher/foreground.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/
    - assets/icons/
    - assets/developers/
    - assets/icnfb.png
    - assets/icngmail.png
    - assets/icn_twitter.png
    - assets/imgforgot.png
    - assets/logo_splash.png
    - assets/icn_coming_soon.png
    - assets/drawer_design1.png
    - assets/drawer_design 2.png
    - assets/drawer_design 3.png

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Changa
  #     fonts:
  #       - asset: assets/fonts/Changa-Regular.ttf
  #       - asset: assets/fonts/Changa-SemiBold.ttf
  #         weight: 600
  #         - asset: assets/fonts/Changa-Bold.ttf
  #         weight: 700
  #          - family: Cairo
  #     fonts:
  #       - asset: assets/fonts/Cairo-Regular.ttf
  #       - asset: assets/fonts/Cairo-SemiBold.ttf
  #         weight: 600
  #         - asset: assets/fonts/Cairo-Bold.ttf
  #         weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
